runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /styles
  static_dir: styles

- url: .*
  script: routes.app


libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
